---
title: "Yellow Rail in Alberta's Oil Sands Region"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

<style>
.datatables{
    overflow: auto;
}
</style>

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

# Load packages
library(tidyverse)
library(flexdashboard)
library(here)
library(leaflet)
library(leaflet.extras)
library(raster)
library(crosstalk)
# library(shiny)
library(DT)
library(sf)
library(RColorBrewer)
library(knitr)

# select <- dplyr::select

# Import data

# Preferred habitat raster (LAPR)
ras_prefhab <- raster(here("./data/base/spatial/yera_prefhab_250m.tif"))
# Abundance predictions (McClelland Lake)
ras_pred <- raster(here("./data/base/spatial/final_yera_pred_mcclelland.tif"))

# Alberta's OSR
sf_osr <- st_read(here("./data/base/spatial/AB_OSR.shp"), quiet = TRUE)

# Lease sites
sf_lease <- st_read(here("./data/base/spatial/AB_lease-sites.shp"), quiet = TRUE) %>%
  dplyr::select(OBJECTID, Project_Na, Scheme_Pro) %>%
  mutate_if(is.factor, as.character) %>%
  mutate(Name = ifelse(is.na(Project_Na), Scheme_Pro, "Jackpine Mine Phase 2")) %>%
  dplyr::select(OBJECTID, Name) %>%
  # Choose only relevant ones near McClelland Lake Fen
  filter(str_detect(Name, "Fort|Aurora|Muskeg|Jackpine|Kearl")) %>%
  st_transform("+init=epsg:4326") %>%
  # Join in Tabulate Area results from ArcGIS re: habitat suitability
  left_join(read_csv(here("./data/base/hab-suit_lease_tab-area.csv")))

# Site metadata
df_meta <- read_csv(here("./data/lookup/yera_ss-meta_2013-18.csv"))
# YERA occupancy
df_occupy <- read_csv(here("./data/processed/yera_occupy_2013-19_new.csv"))

```

```{r prep-data, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

df_occ_summary <- df_occupy %>%
  mutate(occupied = ifelse(occupied == 1, TRUE, FALSE)) %>%
  group_by(ss, year) %>%
  summarise(yera_occupied = ifelse(any(occupied), TRUE, FALSE)) %>%
  ungroup() %>%
  mutate(yera_occupied = as.factor(ifelse(is.na(yera_occupied), "NOT SURVEYED", yera_occupied)),
         yera_occupied = fct_relevel(yera_occupied, "TRUE")) %>%
  left_join(df_meta, by = "ss") %>%
  rename(lat = latit, long = longit) %>%
  dplyr::select(Site = ss, year, lat, long, wetland, yera_occupied)

# Create df of lease centroids for labels
df_centers <- sf_lease %>%
  st_centroid() %>%
  as_Spatial()

# Create palette for site occupancy 
pal1 <- colorFactor(palette = c("yellow", "#7f2704", "grey50"), 
                   domain = df_occ_summary$yera_occupied)

# Convert to SharedData object for crosstalk capability
shared_ss <- SharedData$new(df_occ_summary)

```

Column {data-width=650, .tabset}
-----------------------------------------------------------------------

### Key Breeding Sites in the OSR

```{r include=TRUE, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

# Leaflet map
sf_osr %>%
  st_transform("+init=epsg:4326") %>%
  leaflet() %>%
  addTiles() %>%
  addProviderTiles("Stamen.Terrain") %>%
  addProviderTiles("Esri.WorldImagery", group = "Satellite Imagery") %>%
  addFullscreenControl() %>%
  addResetMapButton() %>%
  addScaleBar(position = "bottomleft",
              options = scaleBarOptions(imperial = FALSE)) %>%
  setView(lng = -111.64, lat = 56.31, zoom = 7) %>%
  addMapPane(name = "OSR Boundary", zIndex = 410) %>%
  addMapPane(name = "Lease Boundaries", zIndex = 420) %>%
        
  # Add OSR polygon
  addPolylines(color = "#0a0909", weight = 2.5, smoothFactor = 0.2, 
               opacity = 3.0, fill = FALSE, 
               group = "Alberta Oil Sands Region Boundary",
               options = leafletOptions(pane = "OSR Boundary")) %>%
  
  # Add lease sites polygon
  addPolylines(data = sf_lease, color = "#0a0909", weight = 1.5, smoothFactor = 0.2,
               opacity = 3.0, fill = FALSE,
               group = "Nearby Oil Sands Lease Sites",
               options = leafletOptions(pane = "Lease Boundaries")) %>%
  
  # Lease labels
  addLabelOnlyMarkers(data = df_centers, label = ~Name, 
                      group = "Nearby Oil Sands Lease Sites",
                      labelOptions = labelOptions(
                        noHide = TRUE, textOnly = FALSE, textsize = "10px",
                        opacity = 1, offset = c(0,0)
                      )) %>%
        
  # Add markers for survey stations
  addCircleMarkers(data = shared_ss, color = ~pal1(yera_occupied),
                   stroke = FALSE, fillOpacity = 1, radius = 7,
                   popup = paste("Site Code:", "<b>", df_occ_summary$Site)) %>%
        
  # Add legend
  addLegend(data = shared_ss, pal = pal1, values = ~yera_occupied,
            position = "bottomright", opacity = 1.0,
            title = "Yellow Rail Detection") %>%
        
  # Add layers control
  addLayersControl(overlayGroups = c("Alberta Oil Sands Region Boundary",
                                      "Satellite Imagery",
                                     "Nearby Oil Sands Lease Sites"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
        
  hideGroup(c("Satellite Imagery", "Nearby Oil Sands Lease Sites"))

```

### Habitat Suitability in the OSR

```{r}

# Define palette
pal_rev <- rev(brewer.pal(9, "RdBu"))
pal1 <- colorNumeric(palette = pal_rev, 
                         domain = values(ras_prefhab), 
                         na.color = "transparent")

# Leaflet map
map_prefhab <- sf_osr %>%
  st_transform("+init=epsg:4326") %>%
  leaflet() %>%
  addTiles() %>%
  addProviderTiles("Stamen.Terrain") %>%
  addFullscreenControl() %>%
  addResetMapButton() %>%
  addScaleBar(position = "bottomleft",
              options = scaleBarOptions(imperial = FALSE)) %>%
  setView(lng = -111.64, lat = 56.31, zoom = 7) %>%
  addMapPane(name = "OSR Boundary", zIndex = 410) %>%
  addMapPane(name = "Lease Boundaries", zIndex = 420) %>%
  
  # Add OSR polygon
  addPolylines(color = "#0a0909", weight = 2, smoothFactor = 0.2, 
               opacity = 3.0, fill = FALSE, 
               group = "Alberta Oil Sands Region Boundary",
               options = leafletOptions(pane = "OSR Boundary")) %>%
  
  # Add lease sites polygon
  addPolylines(data = sf_lease, color = "#0a0909", weight = 2.5, smoothFactor = 0.2,
               opacity = 3.0, fill = FALSE,
               group = "Nearby Oil Sands Lease Sites",
               options = leafletOptions(pane = "Lease Boundaries")) %>%
  
  # Lease labels
  addLabelOnlyMarkers(data = df_centers, label = ~Name, 
                      group = "Nearby Oil Sands Lease Sites",
                      labelOptions = labelOptions(
                        noHide = TRUE, textOnly = FALSE, textsize = "10px",
                        opacity = 1, offset = c(0,0)
                      )) %>%

  # Add raster layer
  addRasterImage(ras_prefhab, colors = pal1, opacity = 1,
                 group = "Predicted Habitat Suitability") %>%
  
  # Add legend
  addLegend(pal = pal1, values = values(ras_prefhab), opacity = 1,  
            title = "Predicted Habitat Suitability", position = "bottomright",
            group = "Predicted Habitat Suitability") %>%
  
  # Layers Control
  addLayersControl(overlayGroups = c("Predicted Habitat Suitability",
                                     "Alberta Oil Sands Region Boundary",
                                     "Nearby Oil Sands Lease Sites"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
  
  hideGroup("Nearby Oil Sands Lease Sites")

map_prefhab

```

### Datatable

```{r include=TRUE, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

datatable(shared_ss)

```


Column {data-width=350}
-----------------------------------------------------------------------

### Site Selection Parameters

```{r include=TRUE, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

filter_checkbox("yera_occupied", "Yellow Rail Detection", shared_ss, ~yera_occupied)

filter_select("year", "Survey Year", shared_ss, ~year, multiple = FALSE, selected = 2013)

filter_checkbox("wetland", "Regionally Important Wetlands", shared_ss, ~wetland)

```

### Datatable

```{r include=FALSE, echo=FALSE, message=FALSE, warning=FALSE, eval=FALSE}

DT::datatable(
  df_occ_summary, 
  filter = "top", 
  rownames = FALSE,
  class = 'cell-border-stripe',
  colnames = c("Site Code", "Survey Year", "Lat", "Long", "Wetland", "Occupancy Status"))
  
  
          # options = list(pageLength = 20, scrollX = TRUE))

```















